name: Digitraffic
baseurl:
repository: finnishtransportagency/digitraffic
gems:
  - jekyll-babel
sass:
  sass_dir: _scss
compress_html:
  clippings: all
exclude:
  - docs
  - digitraffic.iml
  - Gemfile
  - gulpfile.js
  - metadata
  - node_modules
  - package-lock.json
  - package.json
  - README.md
  - update-swagger.sh
collections:
  applications:
    output: true
    permalink: /sovellukset/:name.html
  developments:
    output: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: "img"
    values:
      image: true
  -
    scope:
      path: ""
      type: "applications"
    values:
      layout: "application"
      hero-image: "code"
      logo: "application-default-logo.svg"
  -
    scope:
      path: ""
    values:
      lang: "fi"

# Translations below
t:
  # Traffic types
  tieliikenne:
    en: "Road"
    fi: "Tieliikenne"
  rautatieliikenne:
    en: "Railroad"
    fi: "Rautatieliikenne"
  meriliikenne:
    en: "Maritime"
    fi: "Meriliikenne"
  # Post types
  artikkelit:
    en: "Article"
    fi: "Artikkelit"
  tapahtumat:
    en: "Events"
    fi: "Tapahtumat"
  tiedotteet:
    en: "News"
    fi: "Tiedotteet"
  # Menu
  menu:
    en: "Menu"
    fi: "Valikko"
  search:
    en: "Search"
    fi: "Haku"
  search-placeholder:
    en: "What are you looking for?"
    fi: "Mitä etsit?"
  # Posts
  filter-news:
    en: "Filter news"
    fi: "Rajaa tiedotelistaa"
  tag:
    en: "Tag"
    fi: "Avainsana"
  traffictype:
    en: "Traffic type"
    fi: "Liikennetyyppi"
  year:
    en: "Year"
    fi: "Vuosi"