name: Digitraffic
baseurl:
repository: finnishtransportagency/digitraffic
gems:
  - jekyll-babel
sass:
  sass_dir: _scss
compress_html:
  clippings: all
exclude:
  - docs
  - digitraffic.iml
  - Gemfile
  - gulpfile.js
  - metadata
  - node_modules
  - package-lock.json
  - package.json
  - README.md
  - update-swagger.sh
collections:
  applications:
    output: true
    permalink: /sovellukset/:name.html
  developments:
    output: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: "img"
    values:
      image: true
  -
    scope:
      path: ""
      type: "applications"
    values:
      layout: "application"
      hero-image: "code"
      logo: "application-default-logo.svg"
  -
    scope:
      path: ""
    values:
      language: "fin"